// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aviu00 <93730715+Aviu00@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Misandry <mary@thughunt.ing>
// SPDX-FileCopyrightText: 2025 gus <august.eymann@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.Humanoid;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client._Goobstation.Wizard.MagicMirror;

[GenerateTypedNameReferences]
public sealed partial class WizardMirrorWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    public HashSet<ProtoId<SpeciesPrototype>>? AllowedSpecies;

    public event Action? Save;

    public HumanoidCharacterProfile? Profile;

    public HumanoidCharacterProfile? LoadedProfile;

    private readonly List<SpeciesPrototype> _species = new();

    private Direction _previewRotation = Direction.North;

    private bool _isDirty;

    public WizardMirrorWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SaveButton.OnPressed += _ =>
        {
            Save?.Invoke();
            Close();
        };

        #region Left

        #region Name

        NameEdit.OnTextChanged += args => { SetName(args.Text); };
        NameRandomize.OnPressed += _ => RandomizeName();
        RandomizeEverythingButton.OnPressed += _ => { RandomizeEverything(); };

        #endregion Name

        #region Appearance

        TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));

        #region Sex

        SexButton.OnItemSelected += args =>
        {
            SexButton.SelectId(args.Id);
            SetSex((Sex) args.Id);
        };

        #endregion Sex

        #region Gender

        PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int) Gender.Male);
        PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int) Gender.Female);
        PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int) Gender.Epicene);
        PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int) Gender.Neuter);

        PronounsButton.OnItemSelected += args =>
        {
            PronounsButton.SelectId(args.Id);
            SetGender((Gender) args.Id);
        };

        #endregion Gender

        RefreshSpecies();

        SpeciesButton.OnItemSelected += args =>
        {
            SpeciesButton.SelectId(args.Id);
            SetSpecies(_species[args.Id].ID);
            OnSkinColorOnValueChanged();
        };

        #region Skin

        Skin.OnValueChanged += _ =>
        {
            OnSkinColorOnValueChanged();
        };

        #endregion

        #region Eyes

        EyeColorPicker.OnEyeColorPicked += newColor =>
        {
            if (Profile is null)
                return;
            Profile = Profile.WithCharacterAppearance(
                Profile.Appearance.WithEyeColor(newColor));
            ReloadProfilePreview();
        };

        #endregion Eyes

        #endregion Appearance

        #region Dummy

        SpriteRotateLeft.OnPressed += _ =>
        {
            _previewRotation = _previewRotation.TurnCw();
            SetPreviewRotation(_previewRotation);
        };
        SpriteRotateRight.OnPressed += _ =>
        {
            _previewRotation = _previewRotation.TurnCcw();
            SetPreviewRotation(_previewRotation);
        };

        #endregion Dummy

        #endregion Left

        IsDirty = false;
    }

    /// <summary>
    /// Refreshes the species selector.
    /// </summary>
    public void RefreshSpecies()
    {
        SpeciesButton.Clear();
        _species.Clear();

        if (AllowedSpecies != null)
        {
            _species.AddRange(_prototypeManager.EnumeratePrototypes<SpeciesPrototype>()
                .Where(o => AllowedSpecies.Contains(o.ID)));
            if (Profile != null && _prototypeManager.TryIndex(Profile.Species, out var prototype) && !_species.Contains(prototype))
                _species.Add(prototype);
        }
        else
            _species.AddRange(_prototypeManager.EnumeratePrototypes<SpeciesPrototype>().Where(o => o.RoundStart));
        var speciesIds = _species.Select(o => o.ID).ToList();

        for (var i = 0; i < _species.Count; i++)
        {
            var name = Loc.GetString(_species[i].Name);
            SpeciesButton.AddItem(name, i);

            if (Profile?.Species.Equals(_species[i].ID) == true)
            {
                SpeciesButton.SelectId(i);
            }
        }

        // If our species isn't available then reset it to default.
        if (Profile != null)
        {
            if (!speciesIds.Contains(Profile.Species))
            {
                SetSpecies(HumanoidCharacterProfile.DefaultSpecies);
            }
        }
    }

    private void SetDirty()
    {
        // If it equals default then reset the button.
        if (Profile == null || LoadedProfile == null || LoadedProfile.MemberwiseEquals(Profile))
        {
            IsDirty = false;
            return;
        }

        IsDirty = true;
    }

    /// <summary>
    /// Reloads the entire dummy entity for preview.
    /// </summary>
    /// <remarks>
    /// This is expensive so not recommended to run if you have a slider.
    /// </remarks>
    private void ReloadPreview()
    {
        if (Profile == null || !_prototypeManager.HasIndex(Profile.Species))
            return;

        SpriteView.LoadPreview(Profile);
        SetDirty();
    }

    /// <summary>
    /// Sets the editor to the specified profile with the specified slot.
    /// </summary>
    public void SetProfile(HumanoidCharacterProfile? profile)
    {
        Profile = profile?.Clone();
        IsDirty = false;

        UpdateNameEdit();
        UpdateSexControls();
        UpdateGenderControls();
        UpdateSkinColor();
        UpdateEyePickers();
        UpdateSaveButton();

        RefreshSpecies();
        ReloadPreview();
    }


    private void ReloadProfilePreview()
    {
        if (Profile == null)
            return;

        SpriteView.ReloadProfilePreview(Profile);
        SetDirty();
    }

    // Allow all the possible skin colors
    private void OnSkinColorOnValueChanged()
    {
        if (Profile is null)
            return;

        if (!RgbSkinColorContainer.Visible)
        {
            Skin.Visible = false;
            RgbSkinColorContainer.Visible = true;
        }

        Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(new Color(Skin.Value / 100f, Skin.Value / 100f, Skin.Value / 100f)));

        ReloadProfilePreview();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        ReloadPreview();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        SpriteView.ClearPreview();
    }

    private void SetSex(Sex newSex)
    {
        Profile = Profile?.WithSex(newSex);
        // for convenience, default to most common gender when new sex is selected
        switch (newSex)
        {
            case Sex.Male:
                Profile = Profile?.WithGender(Gender.Male);
                break;
            case Sex.Female:
                Profile = Profile?.WithGender(Gender.Female);
                break;
            default:
                Profile = Profile?.WithGender(Gender.Epicene);
                break;
        }

        UpdateGenderControls();
        ReloadPreview();
    }

    private void SetGender(Gender newGender)
    {
        Profile = Profile?.WithGender(newGender);
        ReloadPreview();
    }

    private void SetSpecies(string newSpecies)
    {
        Profile = Profile?.WithSpecies(newSpecies);
        OnSkinColorOnValueChanged(); // Species may have special color prefs, make sure to update it.
        UpdateSexControls(); // update sex for new species
        ReloadPreview();
    }

    private void SetName(string newName)
    {
        Profile = Profile?.WithName(newName);
        SetDirty();

        if (!IsDirty)
            return;

        SpriteView.SetName(newName);
    }

    public bool IsDirty
    {
        get => _isDirty;
        set
        {
            if (_isDirty == value)
                return;

            _isDirty = value;
            UpdateSaveButton();
        }
    }

    private void UpdateNameEdit()
    {
        NameEdit.Text = Profile?.Name ?? "";
    }

    private void UpdateSexControls()
    {
        if (Profile == null)
            return;

        SexButton.Clear();

        var sexes = new List<Sex>();

        if (_prototypeManager.TryIndex(Profile.Species, out var speciesProto))
        {
            foreach (var sex in speciesProto.Sexes)
            {
                sexes.Add(sex);
            }
        }
        else
        {
            sexes.Add(Sex.Unsexed);
        }

        // add button for each sex
        foreach (var sex in sexes)
        {
            SexButton.AddItem(Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLower()}-text"), (int) sex);
        }

        if (sexes.Contains(Profile.Sex))
            SexButton.SelectId((int) Profile.Sex);
        else
            SexButton.SelectId((int) sexes[0]);
    }

    private void UpdateSkinColor()
    {
        if (Profile == null)
            return;

        Skin.Value = Profile.Appearance.SkinColor.R * 100f;
    }

    private void UpdateGenderControls()
    {
        if (Profile == null)
        {
            return;
        }

        PronounsButton.SelectId((int) Profile.Gender);
    }

    private void UpdateEyePickers()
    {
        if (Profile == null)
        {
            return;
        }

        EyeColorPicker.SetData(Profile.Appearance.EyeColor);
    }

    private void UpdateSaveButton()
    {
        SaveButton.Disabled = Profile is null || !IsDirty;
    }

    private void SetPreviewRotation(Direction direction)
    {
        SpriteView.OverrideDirection = (Direction) ((int) direction % 4 * 2);
    }

    private void RandomizeEverything()
    {
        Profile = HumanoidCharacterProfile.Random();
        if (LoadedProfile != null)
            Profile = Profile.WithAge(LoadedProfile.Age);
        SetDirty();
        SetProfile(Profile);
    }

    private void RandomizeName()
    {
        if (Profile == null)
            return;
        var name = HumanoidCharacterProfile.GetName(Profile.Species, Profile.Gender);
        SetName(name);
        UpdateNameEdit();
    }
}
